import { MenuProvider } from '@/contexts/menu'
import type { Metadata } from 'next'
import { Poppins, Raleway, Roboto } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

export const raleway = Raleway({
  weight: '800',
  variable: '--font-raleway',
  subsets: ['latin'],
})

export const rajdhani = Poppins({
  weight: '400',
  variable: '--font-rajdhani',
  subsets: ['latin'],
})

export const roboto = Roboto({
  weight: '400',
  variable: '--font-roboto',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.className}`}>
      <body>
        <MenuProvider>{children}</MenuProvider>
      </body>
    </html>
  )
}
